// components/about/Services.vue
<template>
	<div class="about-services">
		<div class="row">
			<div class="col col-12 col-md-6" v-for='service in services' :key='service.title'>
				<div class="about-services__item">
					<i :class="service.icon"></i>
					<h4 class="about-services__item-title">{{service.title}}</h4>
					<p class="about-services__item-descr">{{service.excerpt}}</p>
				</div>
			</div>			
		</div>
	</div>
</template>
<script>
	export default {
		name: 'services',
		data() {
			return {
				services: [
					{
						icon: 'fab fa-vuejs',
						image: '',
						title: 'Build Single-Page Application',
						excerpt: 'You`ve saw many times these cool sites which don`t reload after going to another page? It`s a SPA? Do you want the same? Just write me.',
						describe: 'You`ve saw many times these cool sites which don`t reload after going to another page? It`s a SPA? Do you want the same? Just write me.',
					},
					{
						icon: 'fab fa-wordpress',
						image: '',
						title: 'WordPress Theme developing',
						excerpt: 'You have a website, but you don`t imagine how change content? So, in this case, you need a content management system and I`ll help you with it',
						describe: 'Writers and stars of Veep have res ponded incredulously to the news an Australian politician required stitches after knocking himself unconscious.',
					},
					{
						icon: 'fas fa-object-ungroup',
						title: 'Creating sites from exsisting design',
						excerpt: 'Do you have a design and you don`t know how make it alive? I can help you with this problem.',
						describe: 'Writers and stars of Veep have res ponded incredulously to the news an Australian politician required stitches after knocking himself unconscious.',
					},
					
					{
						icon: 'fas fa-cogs',
						image: '',
						title: 'Search Engine Optimization',
						excerpt: 'Would you like to see your website on the first position in search results? You are in the right place :)',
						describe: 'Writers and stars of Veep have res ponded incredulously to the news an Australian politician required stitches after knocking himself unconscious.',
					},
					{
						icon: 'fas fa-medkit',
						title: 'Quick Support',
						excerpt: 'Do you have a design and you don`t know how make it alive? I can help you with this problem.',
						description: 'Lorem Ipsum is simply dummy text of the Lorem has been the industry`s standard dummy text ever.',
					},
				]
			}
		}
	}
</script>
<style lang='scss'>
	.about {
		&-services {
			padding-top: 110px;
			padding-bottom: 105px;
			@include md-size-max {
			  	padding-top: 80px;
			  	padding-bottom: 60px;
			}
			@include sm-size-max {
			  	padding-top: 80px;
			  	padding-bottom: 40px;
			}
			.col:last-child {
				margin-left: 25%;
				@include sm-size-max {
					margin-left: 0;
				}
			} 
			&__item {
				text-align: center;
				position: relative;
				padding: 30px;
				background-color: #070708;
				-webkit-transition: all .3s ease-in-out;
				transition: all .3s ease-in-out;
				border-radius: 10px;
				margin-bottom: 20px;
				i {
					position: relative;
					width: 70px;
					height: 70px;
					font-size: 25px;
					line-height: 70px;
					color: $white;
					background-color: #0e0f10;
					-webkit-border-radius: 50%;
					border-radius: 50%;
					text-align: center;
					
					
					&:hover {
						&::after {
							content: '';
							position: absolute;
							width: 60px;
							height: 60px;
							top: 5px;
							left: calc(50% - 30px);
							-webkit-border-radius: 100%;
							border-radius: 100%;
							border: 1px solid $accent;
							-webkit-animation: zoomIn .3s ease;
							animation: zoomIn .3s ease;
						}
					}
				}
				&-title {
					padding-top: 20px;
					padding-bottom: 20px;
					color: $white;
				}

				&-descr {
					color: $white;
				}
			}
			

			@keyframes zoomIn {
				from {
					opacity: 0;
					-webkit-transform: scale3d(0.3, 0.3, 0.3);
							transform: scale3d(0.3, 0.3, 0.3);
				}
				50% {
					opacity: 1;
				}
			}
		}
	}
</style>

// src/components/sections/Services/index.jsx
import React from 'react';
import { Container, Grid, SectionWrap } from '../../../layout/layout.styles';
import { SectionHeading } from '../../common/SectionHeading';
import { ServicesList } from './services.styles';
import { ServiceItem } from './ServicesItem';
import {
  IReact, IWordpress, IMobile, IPalette, ISEO,
} from '../../common/Icons';

const servicesInfo = [
  {
    icon: IReact,
    title: 'Build Single-Page Application',
    description: `You've saw many times these cool sites which don't reload after going to another page? It's a SPA? 
        Do you want the same? Just write me.`,
  }, {
    icon: IMobile,
    title: 'Mobile app developing',
    description: 'Are you looking for an mobile app? And you want it to work on Android and iOS. Let\'s chat!',
  },
  {
    icon: IWordpress,
    title: 'Wordpress Developing',
    description: 'You have a website, but you don`t imagine how change content? So, in this case, you need a content management system and I`ll help you with it',
  }, {
    icon: IPalette,
    title: 'Creating sites from existing design',
    description: 'Do you have a design and you don`t know how make it alive? I can help you with this problem.',
  }, {
    icon: ISEO,
    title: 'Search Engine Optimization',
    description: 'Would you like to see your website on the first position in search results? You are in the right place :)',
  },
];

export const Services = () => (
  <Container>
    <SectionWrap id="services">
      <SectionHeading align="center" title="Services" subtitle="The skills to pay the bills." />
      <ServicesList>
        <Grid columns="1fr 1fr 1fr">
          {servicesInfo.map((service) => (
            <ServiceItem
              Icon={service.icon}
              title={service.title}
              description={service.description}
            />
          ))}
        </Grid>
      </ServicesList>
    </SectionWrap>
  </Container>
);
